#pragma once
#include "DataStructures/DataStructure.h"
#include "DataStructures/Array.h"
#include "DataStructures/DynamicArray.h"
#include "DataStructures/Matrix.h"
#include "DataStructures/DynamicMatrix.h"
#include "DataStructures/LinkedList.h"
#include "DataStructures/DoublyLinkedList.h"
#include "DataStructures/Stack.h"
#include "DataStructures/Queue.h"
#include "DataStructures/BinaryTree.h"
#include "DataStructures/Graph.h"

#include "Algorithms/Algorithm.h"
#include "Algorithms/Sorter.h"
#include "Algorithms/BubbleSort.h"
#include "Algorithms/SelectionSort.h"
#include "Algorithms/InsertionSort.h"