#pragma once
#include "Logger/Logger.h"

#include "DataStructures/Iterator/Iterator.h"
#include "DataStructures/Iterator/Iterable.h"
#include "DataStructures/Iterator/ReverseIterator.h"
#include "DataStructures/Iterator/ReverseIterable.h"

#include "DataStructures/DataStructure.h"
#include "DataStructures/Array.h"
#include "DataStructures/DynamicArray.h"
#include "DataStructures/Matrix.h"
#include "DataStructures/DynamicMatrix.h"
#include "DataStructures/LinkedList.h"
#include "DataStructures/DoublyLinkedList.h"
#include "DataStructures/CircularLinkedList.h"
#include "DataStructures/Stack.h"
#include "DataStructures/Queue.h"
#include "DataStructures/BinaryTree.h"
#include "DataStructures/BinarySearchTree.h"
#include "DataStructures/Graph.h"
#include "DataStructures/HashMap.h"

#include "Algorithms/Algorithm.h"
#include "Algorithms/Sorter.h"
#include "Algorithms/Sorter/Includes.h"
#include "Algorithms/Searcher.h"
#include "Algorithms/Searcher/Includes.h"